version: 0.0.0.{build}
image: Visual Studio 2017


environment:
    matrix:
        - MBITS: 32
          PYTHON_VERSION: 37
          MSVC_VERSION: 15


install:
    # configure variables
    - ps: |
        if ($env:MBITS -eq "32") {
            echo "Architecture set to 32 bit."
            $env:PYTHON_PATH="C:/Python$env:PYTHON_VERSION"
            $env:CMAKE_GENERATOR="Visual Studio $env:MSVC_VERSION"
        } elseif ($env:MBITS -eq "64") {
            echo "Architecture set to 64 bit."
            $env:PYTHON_PATH="C:/Python$env:PYTHON_VERSION-x64"
            $env:CMAKE_GENERATOR="Visual Studio $env:MSVC_VERSION Win64"
        } else {
            echo "No architecture set. Build will be canceled."
        }
    - SET PIP_PATH=%PYTHON_PATH%/Scripts
    - SET PATH=%PYTHON_PATH%;%PIP_PATH%;%PATH%
    # install python dependencies
    - cmd: pip install parso==0.3.1
    - cmd: pip install jedi==0.13.2
    - cmd: pip install pyinstaller
    # prepare for SourcetrailDB build
    - cmd: git clone -q --branch=master https://github.com/CoatiSoftware/SourcetrailDB.git
    # Install SWIG by Choco
    - ps: choco install -y --no-progress swig


before_build:
    - ps: $env:PACKAGE_VERSION = Get-Content -Path ./version.txt
    - ps: echo "Package version is $env:PACKAGE_VERSION"
    - ps: $env:MAJOR_VERSION = $env:PACKAGE_VERSION.Split("_")[0].TrimStart("v")
    - ps: echo "Major version is $env:MAJOR_VERSION"
    - ps: $env:DATABASE_VERSION = $env:PACKAGE_VERSION.Split("_")[1].TrimStart("db")
    - ps: echo "Database version is $env:DATABASE_VERSION"
    - ps: $env:PATCH_VERSION = $env:PACKAGE_VERSION.Split("_")[2].TrimStart("p")
    - ps: echo "Patch version is $env:PATCH_VERSION"
    - ps: $env:BUILD_VERSION = $env:MAJOR_VERSION + "." + $env:DATABASE_VERSION + "." + $env:PATCH_VERSION + "." + $env:APPVEYOR_BUILD_NUMBER
    - ps: echo "update build version to $env:BUILD_VERSION"
    - ps: Update-AppveyorBuild -Version $env:BUILD_VERSION


build_script:
    - cd SourcetrailDB
    - mkdir build
    - cd build
    - cmake -G "%CMAKE_GENERATOR%" ../ -DBUILD_BINDINGS_PYTHON=ON -DPYTHON_LIBRARY="%PYTHON_PATH%/libs/python%PYTHON_VERSION%.lib"
    - msbuild /p:configuration=Release /v:m ALL_BUILD.vcxproj
    - cd ..
    - cd ..
    - ps: |
        copy SourcetrailDB/build/bindings_python/sourcetraildb.py ./
        copy SourcetrailDB/build/bindings_python/Release/_sourcetraildb.pyd ./


after_build:
    - cmd: pyinstaller freezing.spec
    - ps: $env:PACKAGE_NAME = 'SourcetrailPythonIndexer_' + $env:PACKAGE_VERSION + '-windows'
    - ps: echo $env:PACKAGE_NAME
    - mkdir artifacts
    - cd artifacts
    - mkdir %PACKAGE_NAME%
    - cd %PACKAGE_NAME%
    - mkdir license
    - cd license
    - mkdir 3rd_party_licenses
    - cd ..
    - cd ..
    - cd ..
    - ps: Copy-Item -Path dist/SourcetrailPythonIndexer/* -Recurse -Destination artifacts/$env:PACKAGE_NAME
    - ps: copy LICENSE.txt artifacts/$env:PACKAGE_NAME/license/
    - ps: copy SourcetrailDB/LICENSE.txt artifacts/$env:PACKAGE_NAME/license/3rd_party_licenses/license_sourcetraildb.txt
    - ps: copy SourcetrailDB/external/cpp_sqlite/license_cpp_sqlite.txt artifacts/$env:PACKAGE_NAME/license/3rd_party_licenses/
    - ps: copy SourcetrailDB/external/json/license_json.txt artifacts/$env:PACKAGE_NAME/license/3rd_party_licenses/


test_script:
    - cmd: python test.py
    - ps: $env:SOURCETRAIL_DB_DATABASE_VERSION = python -c "import sourcetraildb; print(sourcetraildb.getSupportedDatabaseVersion())"
    - ps: |
        if ($env:SOURCETRAIL_DB_DATABASE_VERSION -eq $env:DATABASE_VERSION) {
            echo "SourcetrailPythonIndexer matches SourcetrailDB's database version."
        } else {
            throw "SourcetrailPythonIndexer db version ($env:DATABASE_VERSION) and SourcetrailDB db version ($env:SOURCETRAIL_DB_DATABASE_VERSION) do not match."
        }


artifacts:
    - path: artifacts
      name: $(PACKAGE_NAME)
      type: Zip


deploy:
    provider: GitHub
    artifact: $(PACKAGE_NAME)
    auth_token:
        secure: MB2DqEW2eCwgCYtz/5BEn18XweV4eU760lzt7zpZ9fGEU5mxxhh79FLzK8Ux++09
    on:
        appveyor_repo_tag: true
