version: 0.0.0.{build}
image: Visual Studio 2017


environment:
    matrix:
        - MBITS: 32
          PYTHON_VERSION: 37


install:
    - ps: |
        if ($env:MBITS -eq "32") {
            echo "Architecture set to 32 bit."
            $env:PYTHON_PATH="C:/Python$env:PYTHON_VERSION"
        } elseif ($env:MBITS -eq "64") {
            echo "Architecture set to 64 bit."
            $env:PYTHON_PATH="C:/Python$env:PYTHON_VERSION-x64"
        } else {
            echo "No architecture set. Build will be canceled."
        }
    - SET PIP_PATH=%PYTHON_PATH%/Scripts
    - SET PATH=%PYTHON_PATH%;%PIP_PATH%;%PATH%
    - cmd: pip install parso==0.3.1
    - cmd: pip install jedi==0.13.2
    - cmd: pip install pyinstaller


before_build:
    - ps: $env:PACKAGE_VERSION = Get-Content -Path ./version.txt
    - ps: echo "Package version is $env:PACKAGE_VERSION"
    - ps: $env:MAJOR_VERSION = $env:PACKAGE_VERSION.Split("_")[0].TrimStart("v")
    - ps: echo "Major version is $env:MAJOR_VERSION"
    - ps: $env:DATABASE_VERSION = $env:PACKAGE_VERSION.Split("_")[1].TrimStart("db")
    - ps: echo "Database version is $env:DATABASE_VERSION"
    - ps: $env:PATCH_VERSION = $env:PACKAGE_VERSION.Split("_")[2].TrimStart("p")
    - ps: echo "Patch version is $env:PATCH_VERSION"
    - ps: $env:BUILD_VERSION = $env:MAJOR_VERSION + "." + $env:DATABASE_VERSION + "." + $env:PATCH_VERSION + "." + $env:APPVEYOR_BUILD_NUMBER 
    - ps: echo "update build version to $env:BUILD_VERSION"
    - ps: Update-AppveyorBuild -Version $env:BUILD_VERSION


build_script:
    - ps: |
        $env:SOURCETRAILDB_PATH="sourcetrailbd_python" + $env:PYTHON_VERSION + "_v1_db23_p0-windows-" + $env:MBITS + "bit"
        copy external/$env:SOURCETRAILDB_PATH/sourcetraildb.py ./
        copy external/$env:SOURCETRAILDB_PATH/_sourcetraildb.pyd ./


after_build:
    - cmd: pyinstaller freezing.spec
    - ps: $env:PACKAGE_NAME = 'SourcetrailPythonIndexer_' + $env:PACKAGE_VERSION + '-windows'
    - ps: echo $env:PACKAGE_NAME
    - mkdir artifacts
    - cd artifacts
    - mkdir %PACKAGE_NAME%
    - cd ..
    - ps: Copy-Item -Path dist/SourcetrailPythonIndexer/* -Recurse -Destination artifacts/$env:PACKAGE_NAME


test_script:
    - cmd: python test.py


artifacts:
    - path: artifacts
      name: $(PACKAGE_NAME)
      type: Zip


deploy:
    provider: GitHub
    artifact: $(PACKAGE_NAME)
    auth_token:
        secure: MB2DqEW2eCwgCYtz/5BEn18XweV4eU760lzt7zpZ9fGEU5mxxhh79FLzK8Ux++09
    on:
        appveyor_repo_tag: true
